version: "3"

services:
    postgres:
        container_name: "pgvr-os-db"
        restart: unless-stopped
        image: "postgres:13"
        ports:
            - "15500:5432"
        volumes:
            - "pgdata:/var/lib/postgresql/data/"
        environment:
            POSTGRES_PASSWORD: postgres

volumes:
    pgdata: {}